// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgresql://neondb_owner:npg_47SZYxIayfXg@ep-fragrant-rain-ab9ywz4z.eu-west-2.aws.neon.tech/neondb?sslmode=require",
  },
});
